# Generated by Django 2.2.3 on 2020-07-02 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
