# Generated by Django 2.2.3 on 2020-07-02 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friend_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
