# Generated by Django 2.2.3 on 2020-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_friend_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(related_name='_friend_following_+', to='users.Friend'),
        ),
    ]
