# Generated by Django 2.2.3 on 2020-07-02 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_friend_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
