# Generated by Django 2.2.3 on 2020-07-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
