# Generated by Django 2.2.3 on 2020-07-03 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20200703_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 18, 16, 34, 325635, tzinfo=utc)),
        ),
    ]
