# Generated by Django 2.2.3 on 2020-07-04 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0003_auto_20200703_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 15, 17, 14, 811995, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=datetime.datetime(2020, 7, 4, 15, 17, 14, 811995, tzinfo=utc))),
                ('upvotes', models.IntegerField(default=0)),
                ('answer', models.TextField()),
                ('answered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question_url', models.ForeignKey(on_delete='CASCADE', to='clone.Question')),
            ],
        ),
    ]
