# Generated by Django 2.2.3 on 2020-07-07 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_auto_20200707_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='creator',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 14, 55, 45, 141888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 14, 55, 45, 141888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 14, 55, 45, 140891, tzinfo=utc)),
        ),
    ]
