# Generated by Django 2.2.3 on 2020-07-09 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0011_auto_20200708_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 16, 5, 30, 852200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_url',
            field=models.ForeignKey(on_delete='CASCADE', related_name='comments', to='clone.Answer'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 16, 5, 30, 852200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 16, 5, 30, 851202, tzinfo=utc)),
        ),
    ]
