# Generated by Django 2.2.3 on 2020-07-09 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0015_auto_20200709_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 50, 393597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_url',
            field=models.ForeignKey(on_delete='CASCADE', related_name='ustad', to='clone.Answer'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 50, 394594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 50, 393597, tzinfo=utc)),
        ),
    ]
