# Generated by Django 2.2.3 on 2020-07-10 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0017_auto_20200710_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='down_list',
            field=models.ManyToManyField(related_name='answer_down_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_list',
            field=models.ManyToManyField(related_name='answer_up_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 14, 18, 5, 545377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 14, 18, 5, 545377, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
