# Generated by Django 2.2.3 on 2020-07-11 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0018_auto_20200710_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 5, 52, 53, 525613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 5, 52, 53, 524614, tzinfo=utc)),
        ),
    ]
