# Generated by Django 2.2.3 on 2020-07-11 07:23

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0021_auto_20200711_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 23, 16, 306142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 23, 16, 305145, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 23, 16, 310132, tzinfo=utc))),
                ('comments', models.TextField()),
                ('answer_url', models.ForeignKey(on_delete='CASCADE', to='clone.Answer')),
                ('author', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('comment_list', models.ManyToManyField(related_name='comment_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
