# Generated by Django 2.2.3 on 2020-07-11 07:26

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0022_auto_20200711_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_list',
        ),
        migrations.AddField(
            model_name='answer',
            name='comment_list',
            field=models.ManyToManyField(related_name='comment_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 26, 35, 504386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 26, 35, 508965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 26, 35, 502984, tzinfo=utc)),
        ),
    ]
