# Generated by Django 2.2.3 on 2020-07-12 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0024_auto_20200711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 47, 58, 413109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 47, 58, 416910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 47, 58, 412921, tzinfo=utc)),
        ),
    ]
