# Generated by Django 2.2.3 on 2020-07-15 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0027_auto_20200715_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 9, 22, 445330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.Answer'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 9, 22, 449109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 9, 22, 444211, tzinfo=utc)),
        ),
    ]
