# Generated by Django 2.2.3 on 2020-07-21 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0039_auto_20200721_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 5, 25, 107537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='topics',
            field=models.ManyToManyField(related_name='topic_answers', to='clone.Topics'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 5, 25, 111024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 5, 25, 106540, tzinfo=utc)),
        ),
    ]
