# Generated by Django 2.2.3 on 2020-07-21 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0042_auto_20200721_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 11, 1, 520658, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='topics',
        ),
        migrations.AddField(
            model_name='answer',
            name='topics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_answers', to='clone.Topics'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 11, 1, 523675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 11, 1, 520389, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_questions', to='clone.Topics'),
        ),
    ]
